using version beta & new deployment.yaml

diff --git a/cd/helm/capif/templates/deployment.yaml b/cd/helm/capif/templates/deployment.yaml
--- a/cd/helm/capif/templates/deployment.yaml
+++ b/cd/helm/capif/templates/deployment.yaml
@@ -55,7 +55,7 @@ spec:
         readinessProbe:
           tcpSocket:
             port: 8080
-          initialDelaySeconds: 20
+          initialDelaySeconds: 10
           periodSeconds: 5
       restartPolicy: Always
 ---
@@ -112,29 +112,38 @@ spec:
         - containerPort: 8080
         resources:
             {{- toYaml .Values.apiInvokerManagement.apiInvokerManagement.resources | nindent 12 }}
-#        livenessProbe:
-#          tcpSocket:
-#            port: 8080
-#          initialDelaySeconds: 20
-#          periodSeconds: 5
-        readinessProbe:
+        livenessProbe:
           exec:
             command:
             - sh
             - -c 
             - |-
-              OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_priv_key)
+              OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_pub_key)
               echo "$OUTPUT"
               if [ -z "$OUTPUT" ]; then
-                echo "OUTPUT empty"
+                echo "cannot get the server public key from redis"
                 exit 1;
-              else
-                echo "OUTPUT: $OUTPUT"
-                redis-cli -h redis -p 6379 -n 1 GET  server_pub_key > /usr/src/app/api_invoker_management/pubkey.pem
               fi
-          initialDelaySeconds: 20
+          initialDelaySeconds: 5
           periodSeconds: 5
-          successThreshold: 1
+#        readinessProbe:
+#          exec:
+#            command:
+#            - sh
+#            - -c 
+#            - |-
+#              OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_pub_key)
+#              echo "$OUTPUT"
+#              if [ -z "$OUTPUT" ]; then
+#                echo "OUTPUT empty"
+#                exit 1;
+#              else
+#                echo "OUTPUT: $OUTPUT"
+#                redis-cli -h redis -p 6379 -n 1 GET  server_pub_key > /usr/src/app/api_invoker_management/pubkey.pem
+#              fi
+#          initialDelaySeconds: 20
+#          periodSeconds: 5
+#          successThreshold: 1
       restartPolicy: Always
 ---
 apiVersion: apps/v1
@@ -189,11 +198,6 @@ spec:
         ports:
         - containerPort: 8080
         livenessProbe:
-          tcpSocket:
-            port: 8080
-          initialDelaySeconds: 20
-          periodSeconds: 20
-        readinessProbe:
           exec:
             command:
             - sh
@@ -202,15 +206,29 @@ spec:
               OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_priv_key)
               echo "$OUTPUT"
               if [ -z "$OUTPUT" ]; then
-                echo "OUTPUT empty"
+                echo "cannot get the server public key from redis"
                 exit 1;
-              else
-                echo "OUTPUT: $OUTPUT"
-                redis-cli -h redis -p 6379 -n 1 GET  server_pub_key > /usr/src/app/api_provider_management/pubkey.pem
               fi
-          initialDelaySeconds: 20
+          initialDelaySeconds: 5
           periodSeconds: 5
-          successThreshold: 1
+#        readinessProbe:
+#          exec:
+#            command:
+#            - sh
+#            - -c 
+#            - |-
+#              OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_pub_key)
+#              echo "$OUTPUT"
+#              if [ -z "$OUTPUT" ]; then
+#                echo "OUTPUT empty"
+#                exit 1;
+#              else
+#                echo "OUTPUT: $OUTPUT"
+#                redis-cli -h redis -p 6379 -n 1 GET  server_pub_key > /usr/src/app/api_provider_management/pubkey.pem
+#              fi
+#          initialDelaySeconds: 20
+#          periodSeconds: 5
+#          successThreshold: 1
         resources:
             {{- toYaml .Values.apiProviderManagement.apiProviderManagement.resources | nindent 12 }}
       restartPolicy: Always
@@ -270,7 +288,7 @@ spec:
         readinessProbe:
           tcpSocket:
             port: 8080
-          initialDelaySeconds: 20
+          initialDelaySeconds: 5
           periodSeconds: 5
       restartPolicy: Always
 ---
@@ -329,7 +347,7 @@ spec:
         readinessProbe:
           tcpSocket:
             port: 8080
-          initialDelaySeconds: 20
+          initialDelaySeconds: 5
           periodSeconds: 5
       restartPolicy: Always
 ---
@@ -387,12 +405,7 @@ spec:
         - containerPort: 8080
         resources:
             {{- toYaml .Values.capifSecurity.capifSecurity.resources | nindent 12 }}
-#        livenessProbe:
-#          tcpSocket:
-#            port: 8080
-#          initialDelaySeconds: 20
-#          periodSeconds: 5
-        readinessProbe:
+        livenessProbe:
           exec:
             command:
             - sh
@@ -401,15 +414,29 @@ spec:
               OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_priv_key)
               echo "$OUTPUT"
               if [ -z "$OUTPUT" ]; then
-                echo "OUTPUT empty"
+                echo "cannot get the server private key from redis"
                 exit 1;
-              else
-                echo "OUTPUT: $OUTPUT"
-                redis-cli -h redis -p 6379 -n 1 GET  server_priv_key > /usr/src/app/capif_security/server.key
               fi
-          initialDelaySeconds: 20
+          initialDelaySeconds: 5
           periodSeconds: 5
-          successThreshold: 1
+#        readinessProbe:
+#          exec:
+#            command:
+#            - sh
+#            - -c 
+#            - |-
+#              OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_priv_key)
+#              echo "$OUTPUT"
+#              if [ -z "$OUTPUT" ]; then
+#                echo "OUTPUT empty"
+#                exit 1;
+#              else
+#                echo "OUTPUT: $OUTPUT"
+#                redis-cli -h redis -p 6379 -n 1 GET  server_priv_key > /usr/src/app/capif_security/server.key
+#              fi
+#          initialDelaySeconds: 20
+#          periodSeconds: 5
+#          successThreshold: 1
       restartPolicy: Always
 ---
 apiVersion: apps/v1
@@ -467,7 +494,7 @@ spec:
         readinessProbe:
           tcpSocket:
             port: 8080
-          initialDelaySeconds: 5
+#          initialDelaySeconds: 5
           periodSeconds: 5
       restartPolicy: Always
 ---
@@ -532,32 +559,29 @@ spec:
               OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_priv_key)
               echo "$OUTPUT"
               if [ -z "$OUTPUT" ]; then
-                echo "OUTPUT empty"
+                echo "cannot get the server private key from redis"
                 exit 1;
-              else
-                echo "OUTPUT: $OUTPUT"
-                redis-cli -h redis -p 6379 -n 1 GET  server_priv_key  > /usr/src/app/register_service/server.key
               fi
           initialDelaySeconds: 5
           periodSeconds: 5
-        readinessProbe:
-          exec:
-            command:
-            - sh
-            - -c 
-            - |-
-              OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_priv_key)
-              echo "$OUTPUT"
-              if [ -z "$OUTPUT" ]; then
-                echo "OUTPUT empty"
-                exit 1;
-              else
-                echo "OUTPUT: $OUTPUT"
-                redis-cli -h redis -p 6379 -n 1 GET  server_priv_key  > /usr/src/app/register_service/server.key
-              fi
-          initialDelaySeconds: 90
-          periodSeconds: 5
-          successThreshold: 1
+#        readinessProbe:
+#          exec:
+#            command:
+#            - sh
+#            - -c 
+#            - |-
+#              OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_priv_key)
+#              echo "$OUTPUT"
+#              if [ -z "$OUTPUT" ]; then
+#                echo "OUTPUT empty"
+#                exit 1;
+#              else
+#                echo "OUTPUT: $OUTPUT"
+#                redis-cli -h redis -p 6379 -n 1 GET  server_priv_key  > /usr/src/app/register_service/server.key
+#              fi
+#          initialDelaySeconds: 90
+#          periodSeconds: 5
+#          successThreshold: 1
       restartPolicy: Always
 ---
 apiVersion: apps/v1
@@ -615,7 +639,7 @@ spec:
         readinessProbe:
           tcpSocket:
             port: 8080
-          initialDelaySeconds: 20
+          initialDelaySeconds: 5
           periodSeconds: 5
       restartPolicy: Always
 ---
@@ -678,7 +702,7 @@ spec:
         readinessProbe:
           tcpSocket:
             port: 27017
-          initialDelaySeconds: 5
+#          initialDelaySeconds: 5
           periodSeconds: 5
       restartPolicy: Always
 ---
@@ -745,7 +769,7 @@ spec:
         readinessProbe:
           tcpSocket:
             port: 8081
-          initialDelaySeconds: 10
+#          initialDelaySeconds: 0
           periodSeconds: 5     
       restartPolicy: Always
 ---
@@ -807,11 +831,11 @@ spec:
             port: 8080
           initialDelaySeconds: 20
           periodSeconds: 5
-        readinessProbe:
-          tcpSocket:
-            port: 8080
-          initialDelaySeconds: 60
-          periodSeconds: 5
+#        readinessProbe:
+#          tcpSocket:
+#            port: 8080
+#          initialDelaySeconds: 60
+#          periodSeconds: 5
         resources:
             {{- toYaml .Values.nginx.nginx.resources | nindent 12 }}
       restartPolicy: Always
@@ -871,7 +895,7 @@ spec:
         readinessProbe:
           tcpSocket:
             port: 8080
-          initialDelaySeconds: 20
+          initialDelaySeconds: 5
           periodSeconds: 5
       restartPolicy: Always
 ---
@@ -934,17 +958,13 @@ spec:
         readinessProbe:
           tcpSocket:
             port: 6379
+#          initialDelaySeconds: 5
+          periodSeconds: 5
+        livenessProbe:
+          tcpSocket:
+            port: 6379
           initialDelaySeconds: 5
           periodSeconds: 5
-#        readinessProbe:
-#          exec:
-#            command:
-#            - sh
-#            - -c
-#            - |-
-#              redis-cli ping
-#          initialDelaySeconds: 5
-#          periodSeconds: 5
       restartPolicy: Always
 ---
 apiVersion: apps/v1
@@ -1002,6 +1022,6 @@ spec:
         readinessProbe:
           tcpSocket:
             port: 8080
-          initialDelaySeconds: 20
+          initialDelaySeconds: 5
           periodSeconds: 5
       restartPolicy: Always
