Update deployment.yaml

diff --git a/cd/helm/capif/templates/deployment.yaml b/cd/helm/capif/templates/deployment.yaml
--- a/cd/helm/capif/templates/deployment.yaml
+++ b/cd/helm/capif/templates/deployment.yaml
@@ -113,17 +113,19 @@ spec:
         resources:
             {{- toYaml .Values.apiInvokerManagement.apiInvokerManagement.resources | nindent 12 }}
         livenessProbe:
-          exec:
-            command:
-            - sh
-            - -c 
-            - |-
-              OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_pub_key)
-              echo "$OUTPUT"
-              if [ -z "$OUTPUT" ]; then
-                echo "cannot get the server public key from redis"
-                exit 1;
-              fi
+          tcpSocket:
+            port: 8080
+#          exec:
+#            command:
+#            - sh
+#            - -c 
+#            - |-
+#              OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_pub_key)
+#              echo "$OUTPUT"
+#              if [ -z "$OUTPUT" ]; then
+#                echo "cannot get the server public key from redis"
+#                exit 1;
+#              fi
           initialDelaySeconds: 3
           periodSeconds: 5
 #        readinessProbe:
@@ -198,17 +200,19 @@ spec:
         ports:
         - containerPort: 8080
         livenessProbe:
-          exec:
-            command:
-            - sh
-            - -c 
-            - |-
-              OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_priv_key)
-              echo "$OUTPUT"
-              if [ -z "$OUTPUT" ]; then
-                echo "cannot get the server public key from redis"
-                exit 1;
-              fi
+          tcpSocket:
+            port: 8080
+#          exec:
+#            command:
+#            - sh
+#            - -c 
+#            - |-
+#              OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_priv_key)
+#              echo "$OUTPUT"
+#              if [ -z "$OUTPUT" ]; then
+#                echo "cannot get the server public key from redis"
+#                exit 1;
+#              fi
           initialDelaySeconds: 3
           periodSeconds: 5
 #        readinessProbe:
@@ -406,17 +410,19 @@ spec:
         resources:
             {{- toYaml .Values.capifSecurity.capifSecurity.resources | nindent 12 }}
         livenessProbe:
-          exec:
-            command:
-            - sh
-            - -c 
-            - |-
-              OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_priv_key)
-              echo "$OUTPUT"
-              if [ -z "$OUTPUT" ]; then
-                echo "cannot get the server private key from redis"
-                exit 1;
-              fi
+          tcpSocket:
+            port: 8080
+#          exec:
+#            command:
+#            - sh
+#            - -c 
+#            - |-
+#              OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_priv_key)
+#              echo "$OUTPUT"
+#              if [ -z "$OUTPUT" ]; then
+#                echo "cannot get the server private key from redis"
+#                exit 1;
+#              fi
           initialDelaySeconds: 3
           periodSeconds: 5
 #        readinessProbe:
@@ -551,17 +557,19 @@ spec:
         resources:
             {{- toYaml .Values.jwtauth.jwtauth.resources | nindent 12 }}
         livenessProbe:
-          exec:
-            command:
-            - sh
-            - -c 
-            - |-
-              OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_priv_key)
-              echo "$OUTPUT"
-              if [ -z "$OUTPUT" ]; then
-                echo "cannot get the server private key from redis"
-                exit 1;
-              fi
+          tcpSocket:
+            port: 8080
+#          exec:
+#            command:
+#            - sh
+#            - -c 
+#            - |-
+#              OUTPUT=$(redis-cli -h redis -p 6379 -n 1 GET  server_priv_key)
+#              echo "$OUTPUT"
+#              if [ -z "$OUTPUT" ]; then
+#                echo "cannot get the server private key from redis"
+#                exit 1;
+#              fi
           initialDelaySeconds: 3
           periodSeconds: 5
 #        readinessProbe:
